# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

schedules:
- cron: "0 23 * * 0"
  displayName: "Weekly Sunday build"
  branches:
    include:
    - master
  always: "true"

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:

    - task: Docker@2
      displayName: Login
      inputs:
        containerRegistry: 'dockerhub'
        command: 'login'
    - task: Docker@2
      displayName: Build the API image
      inputs:
        command: buildAndPush
        dockerfile: 'api/Dockerfile'
        containerRegistry: 'dockerhub'
        repository: 'gallows/sw'
        tags: |
          $(tag)-api
          api
    - task: Docker@2
      displayName: Build the App image
      inputs:
        command: buildAndPush
        dockerfile: 'app/Dockerfile'
        containerRegistry: 'dockerhub'
        repository: 'gallows/sw'
        tags: |
          $(tag)-app
          app